platform :ios, '15.0'
use_frameworks!

target 'IMBluetoothKitExample' do
  # Dev against source tree:
#  pod 'IMBluetoothKit', :path => '../'
  pod 'RxSwift', '~> 6.9'
  pod 'RxRelay', '~> 6.9'
  # Binary (GitHub):
  pod 'IMBluetoothKit', :git => 'https://github.com/INMO-X/IMBluetoothKit.git', :tag => '0.1.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Xcode 16+/27 SDK: bump outdated pod deployment targets only.
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 15.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end
