platform :ios, '15.0'
use_frameworks!

target 'IMBluetoothFrameworkExample' do
  # Dev against source tree:
  pod 'IMBluetoothFramework', :path => '../'
  # Explicit pins aligned with IMBluetoothFramework.podspec
  pod 'RxSwift', '~> 6.9'
  pod 'RxRelay', '~> 6.9'
  # After binary publish, switch to:
  # pod 'IMBluetoothFramework', :git => 'https://github.com/INMO-X/IMBluetoothFramework.git', :tag => '0.1.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 15.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end
